//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApplication.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ShapefileInputText {
            get {
                return ((string)(this["ShapefileInputText"]));
            }
            set {
                this["ShapefileInputText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GridInputText {
            get {
                return ((string)(this["GridInputText"]));
            }
            set {
                this["GridInputText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImageInputText {
            get {
                return ((string)(this["ImageInputText"]));
            }
            set {
                this["ImageInputText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FormLocation {
            get {
                return ((global::System.Drawing.Point)(this["FormLocation"]));
            }
            set {
                this["FormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GridfileToClip {
            get {
                return ((string)(this["GridfileToClip"]));
            }
            set {
                this["GridfileToClip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClippingPolygon {
            get {
                return ((string)(this["ClippingPolygon"]));
            }
            set {
                this["ClippingPolygon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ShapefileToGrid {
            get {
                return ((string)(this["ShapefileToGrid"]));
            }
            set {
                this["ShapefileToGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RasterizeInputfile {
            get {
                return ((string)(this["RasterizeInputfile"]));
            }
            set {
                this["RasterizeInputfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BufferShapefile {
            get {
                return ((string)(this["BufferShapefile"]));
            }
            set {
                this["BufferShapefile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SimplifyShapefile {
            get {
                return ((string)(this["SimplifyShapefile"]));
            }
            set {
                this["SimplifyShapefile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AggregateShapefile {
            get {
                return ((string)(this["AggregateShapefile"]));
            }
            set {
                this["AggregateShapefile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal AggregateFieldindex {
            get {
                return ((decimal)(this["AggregateFieldindex"]));
            }
            set {
                this["AggregateFieldindex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DissolveShapefile {
            get {
                return ((string)(this["DissolveShapefile"]));
            }
            set {
                this["DissolveShapefile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal DissolveFieldindex {
            get {
                return ((decimal)(this["DissolveFieldindex"]));
            }
            set {
                this["DissolveFieldindex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClipShapefileInput {
            get {
                return ((string)(this["ClipShapefileInput"]));
            }
            set {
                this["ClipShapefileInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClipShapefileOverlay {
            get {
                return ((string)(this["ClipShapefileOverlay"]));
            }
            set {
                this["ClipShapefileOverlay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IntersectionShapefileFirstInput {
            get {
                return ((string)(this["IntersectionShapefileFirstInput"]));
            }
            set {
                this["IntersectionShapefileFirstInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IntersectionShapefileSecondInput {
            get {
                return ((string)(this["IntersectionShapefileSecondInput"]));
            }
            set {
                this["IntersectionShapefileSecondInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WktShapefile {
            get {
                return ((string)(this["WktShapefile"]));
            }
            set {
                this["WktShapefile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SpatialIndexInputfile {
            get {
                return ((string)(this["SpatialIndexInputfile"]));
            }
            set {
                this["SpatialIndexInputfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OGRInfoInputfile {
            get {
                return ((string)(this["OGRInfoInputfile"]));
            }
            set {
                this["OGRInfoInputfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClosestPointShapefileInput1 {
            get {
                return ((string)(this["ClosestPointShapefileInput1"]));
            }
            set {
                this["ClosestPointShapefileInput1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClosestPointShapefileInput2 {
            get {
                return ((string)(this["ClosestPointShapefileInput2"]));
            }
            set {
                this["ClosestPointShapefileInput2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClipGridByPolygonInputfile {
            get {
                return ((string)(this["ClipGridByPolygonInputfile"]));
            }
            set {
                this["ClipGridByPolygonInputfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TilesInputfile {
            get {
                return ((string)(this["TilesInputfile"]));
            }
            set {
                this["TilesInputfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RasterAInput {
            get {
                return ((string)(this["RasterAInput"]));
            }
            set {
                this["RasterAInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RasterBInput {
            get {
                return ((string)(this["RasterBInput"]));
            }
            set {
                this["RasterBInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RasterCalculatorFormulas {
            get {
                return ((string)(this["RasterCalculatorFormulas"]));
            }
            set {
                this["RasterCalculatorFormulas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RasterCalculatorInput {
            get {
                return ((string)(this["RasterCalculatorInput"]));
            }
            set {
                this["RasterCalculatorInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Filemanager_GridOpen {
            get {
                return ((string)(this["Filemanager_GridOpen"]));
            }
            set {
                this["Filemanager_GridOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Filemanager_OpenFolder {
            get {
                return ((string)(this["Filemanager_OpenFolder"]));
            }
            set {
                this["Filemanager_OpenFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GridProxyInput {
            get {
                return ((string)(this["GridProxyInput"]));
            }
            set {
                this["GridProxyInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReclassifyInput {
            get {
                return ((string)(this["ReclassifyInput"]));
            }
            set {
                this["ReclassifyInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IntersectionShapefileInput {
            get {
                return ((string)(this["IntersectionShapefileInput"]));
            }
            set {
                this["IntersectionShapefileInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClosestPointInput {
            get {
                return ((string)(this["ClosestPointInput"]));
            }
            set {
                this["ClosestPointInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AnalyzeFilesInput {
            get {
                return ((string)(this["AnalyzeFilesInput"]));
            }
            set {
                this["AnalyzeFilesInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AxMapClearInput {
            get {
                return ((string)(this["AxMapClearInput"]));
            }
            set {
                this["AxMapClearInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PostgisInput {
            get {
                return ((string)(this["PostgisInput"]));
            }
            set {
                this["PostgisInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PostGisCreateDb {
            get {
                return ((string)(this["PostGisCreateDb"]));
            }
            set {
                this["PostGisCreateDb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PostGisPrivilegesInput {
            get {
                return ((string)(this["PostGisPrivilegesInput"]));
            }
            set {
                this["PostGisPrivilegesInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PostGisImportSfInput {
            get {
                return ((string)(this["PostGisImportSfInput"]));
            }
            set {
                this["PostGisImportSfInput"] = value;
            }
        }
    }
}
